config/routes.rb
Rails.application.routes.draw do

  
  root 'rounds#index'

  resources :players
  post 'players/:id' => 'players#activate'
end

app/models/bet.rb
# == Schema Information
#
# Table name: bets
#
#  id         :integer          not null, primary key
#  amount     :decimal(, )
#  bet_color  :integer
#  payout     :decimal(, )
#  round_id   :integer
#  player_id  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  status     :integer
#

class Bet < ActiveRecord::Base
  COLORS = [:red, :black, :green]
  STATUS = [:acepted, :rejected]
  enum bet_color: COLORS
  enum status: STATUS

  before_save :verify_minimum_amount_restriction
  before_save :update_player_money, if: :payout?

  belongs_to :round
  belongs_to :player

  validates :amount, :bet_color, :round, :player, presence: true
  validates :round, :player, associated: true

  private

  def verify_minimum_amount_restriction
    if self.amount <= 0
      self.player.broke!
      self.status = "rejected"
      # POR QUE LO ASIGNA DOS VECES?? ESTO SE ESTA EJECUTANDO DOS VECES?
      errors[:amount] << "Doesn't achieve the minimum amount"
    end
  end

  def update_player_money
    if self.payout?
      player = self.player
      player.money += self.payout
      player.save
    end
  end
end

app/models/player.rb
# == Schema Information
#
# Table name: players
#
#  id         :integer          not null, primary key
#  name       :string
#  lastname   :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  money      :decimal(, )      default(10000.0)
#  status     :integer          default(0)
#

class Player < ActiveRecord::Base
  STATUSES = [:available, :broke, :disabled]
  enum status: STATUSES

  before_save :normalize

  has_many :bets
  
  validates :name, presence: true

  def full_name
    [self.name, self.lastname].join(" ")
  end

  def generate_bet bet
    bet.player = self
    bet.bet_color = generate_bet_color
    bet.amount = generate_bet_amount
    if bet.save
      discount_money(bet.amount)
    else
      errors[:base] << "The bet couldn't be saved"
    end
  end

  private

  def generate_bet_color
    color_decision = Random.rand(100.0)
    case color_decision
    when 0..49 
      "red"
    when 49..88
      "black"
    when 88..100 
      "green"
    end
  end

  def generate_bet_amount
    money = self.money
    if money > 1000
      amount_percentage = Random.rand(0.08..0.15)
      money * amount_percentage
    elsif money > 0
      money      
    else
      0
    end
  end

  def discount_money amount
    self.money -= amount
    self.save
  end

  def normalize
    self.name.upcase!
    self.lastname.upcase!
  end

  def self.search(search)
      search.upcase!
      where(["name LIKE ? OR lastname LIKE ?", "%#{search}%", "%#{search}%"])
  end
end

app/models/round.rb
# == Schema Information
#
# Table name: rounds
#
#  id           :integer          not null, primary key
#  total_bet    :decimal(, )
#  spin_result  :integer
#  total_payout :decimal(, )
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Round < ActiveRecord::Base
  COLORS = [:red, :black, :green]
  enum spin_result: COLORS

  has_many :bets

  def generate_round available_players
    generation_logic(available_players)
  end

  def calculate_results
    calculate_total_payout
  end

  private
 
  def generation_logic available_players
    total_bet = 0
    available_players.each do |player|
      bet = self.bets.build
      player.generate_bet(bet)
      total_bet += bet.amount
    end
    self.spin_result = generate_spin_result
    self.total_bet = total_bet
    self.save
  end

  def generate_spin_result
    result_decision = Random.rand(100.0)
    case result_decision
    when 0..49
      "red"
    when 49..98
      "black"
    when 98..100
      "green"
    end
  end

  def calculate_total_payout
    total_payout = 0
    bets = self.bets
    bets.each do |bet|
      if bet.bet_color == self.spin_result && (self.red? || self.black?)
        bet.payout = bet.amount * 2
      elsif bet.bet_color == self.spin_result && self.green?
        bet.payout = bet.amount * 15
      else
        bet.payout = 0
      end
      if bet.save
        total_payout += bet.payout
      else
        errors[:base] << "Bet with id #{bet.id} couldn't be saved"
      end
    end
    self.total_payout = total_payout
    self.save
  end
end

app/models/simulator.rb
class Simulator
  @message = []

  def self.single_simulation
    round = Round.new
    available_players = Player.available
    if available_players.empty?
      @message << "There's not available players"
    else
      round.generate_round(available_players)
      round.calculate_results
      round.save
    end
  end

  def self.assign_money_to_players
    Player.where.not(status: 2).update_all("money = money + 1000, status = 0")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout 'admin_lte_2'

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  def index
    if params[:search]
      @page_header = "Players' Search Result"
      @players = Player.search(params[:search]).page(params[:page]).per(5)
      # http://railscasts.com/episodes/37-simple-search-form
    else
      @page_header = "Players' List"
      @players = Player.page(params[:page]).per(5)
    end
  end

  def new
    @player = Player.new
  end

  def create
    @player = Player.new(player_params)
    if @player.save
      redirect_to players_path, notice: 'Player created! Success'
    else
      flash.now[:alert] = @player.errors.full_messages.join('<br>- ')
      render :new
    end
  end

  def show
    @page_header = "Player Especifications"
    @player = Player.find(params[:id])
  end

  def edit
    @player = Player.find(params[:id])
  end

  def update
    @player = Player.find(params[:id])
    if @player.update(player_params)
      redirect_to player_path(@player), notice: 'Player edited! Success!'
    else
      flash.now[:alert] = @player.errors.full_messages.join('<br>- ')
      render :edit
    end
  end

  def destroy
    @player = Player.find(params[:id])
    if @player.disabled!
      flash[:notice] = 'Player deactivated! Success!'
      redirect_to players_path
    else
      flash[:alert] = @player.errors.full_messages.join('<br>- ')
      redirect_to player_path(@player)
    end
  end

  def activate
    @player = Player.find(params[:id])
    if @player.money > 0
      if @player.available!
        flash[:notice] = 'Player activated! Success!'
        redirect_to players_path
      else
        flash[:alert] = @player.errors.full_messages.join('<br>- ')
        redirect_to player_path(@player)
      end
    else
      if @player.broke!
        flash[:notice] = 'Player activated! Success!'
        redirect_to players_path
      else
        flash[:alert] = @player.errors.full_messages.join('<br>- ')
        redirect_to player_path(@player)
      end
    end
  end

  private

  def player_params
    params.require(:player).permit(:name, :lastname, :money)
  end
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  def index
    @page_header = "Rounds' List"
    @rounds = Round.page(params[:page]).per(5)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_admin_lte_2_header.html.erb
<!-- Main Header -->
<header class="main-header">

  <!-- Logo -->
  <a href="/" class="logo">
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini"><b>R</b>Sim</span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg"><b>Ruleta</b>Simulator</span>
  </a>

  <!-- Header Navbar -->
  <nav class="navbar navbar-static-top" role="navigation">
    <!-- Sidebar toggle button-->
    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>
    <!-- Navbar Right Menu -->
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <!-- User Account Menu -->
        <li class="dropdown user user-menu">
          <!-- Menu Toggle Button -->
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <!-- The user image in the navbar-->
            <%= image_tag "foto.jpg", class: "user-image", alt: "User Image" %>
            <!-- hidden-xs hides the username on small devices so only the image appears. -->
            <span class="hidden-xs">Johanna Salazar</span>
          </a>
          <ul class="dropdown-menu">
            <!-- The user image in the menu -->
            <li class="user-header">
              <%= image_tag "foto.jpg", class: "img-circle", alt: "User" %>
              <p>
                Johanna Salazar - Web Developer
              </p>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/_admin_lte_2_sidebar.html.erb
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">

  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">

    <!-- Sidebar user panel (optional) -->
    <div class="user-panel">
      <div class="pull-left image">
        <%= image_tag "foto.jpg", class: "img-circle", alt: "User Image" %>
      </div>
      <div class="pull-left info">
        <p>Johanna Salazar</p>
      </div>
    </div>

    <!-- search form (Optional) -->
    <form action="/players" method="get" class="sidebar-form">
      <div class="input-group">
        <input type="text" name="search" class="form-control" placeholder="Search a player..."/>
        <span class="input-group-btn">
          <button type='submit' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i></button>
        </span>
      </div>
    </form>
    <!-- /.search form -->

    <!-- Sidebar Menu -->
    <ul class="sidebar-menu">
      <li class="header">Simulation Components</li>
        <!-- Optionally, you can add icons to the links -->
      <li class="active"><a href="/players"><i class='fa fa-link'></i> <span>Players</span></a></li>
      <!-- <li class="treeview">
        <a href="#"><i class='fa fa-link'></i> <span>Multilevel</span> <i class="fa fa-angle-left pull-right"></i></a>
        <ul class="treeview-menu">
          <li><a href="#">Link in level 2</a></li>
          <li><a href="#">Link in level 2</a></li>
        </ul>
      </li> -->
    </ul><!-- /.sidebar-menu -->
  </section>
  <!-- /.sidebar -->
</aside>

app/views/layouts/admin_lte_2.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Ruleta Simulator</title>
  <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
  <link href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet" type="text/css" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.2/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
  <%= csrf_meta_tags %>
</head>

<body class="skin-blue sidebar-mini fixed <%= params[:controller].parameterize %> <%= action_name %>">
  <div class="wrapper">

    <%= render partial: 'layouts/admin_lte_2_header' %>

    <%= render partial: 'layouts/admin_lte_2_sidebar' %>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      <section class="content-header">
        <h1>
          <%= @page_header ? @page_header : " " %>
        </h1>
      </section>

      <!-- Main content -->
      <section class="content">
        <% if notice %>
          <div class="alert alert-success alert-dismissable">
            <i class="fa fa-check"></i>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <b><%= notice %></b>
          </div>
        <% end %>

        <% if alert %>
          <div class="alert alert-danger alert-dismissable">
            <i class="fa fa-ban"></i>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <b><%= alert %></b>
          </div>
        <% end %>
        <%= yield %>
      </section><!-- /.content -->
    </div><!-- /.content-wrapper -->

    <!-- Main Footer -->
    <footer class="main-footer">
      <!-- To the right -->
      <div class="pull-right hidden-xs">
        Ruleta Project
      </div>
      <!-- Default to the left -->
      <strong>Copyright &copy; 2015 <a href="#">Company</a>.</strong> All rights reserved.
    </footer>

  </div><!-- ./wrapper -->

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/players/edit.html.slim
.box
  .box-header.with-border
    h3.box-title Edition of Player
  .box-body
    = simple_form_for @player, defaults: {wrapper_html: {class: "form-group"}} do |player|
      = player.input :name, required: true, label: 'Name', placeholder: 'Name'
      = player.input :lastname, label: 'Last Name', placeholder: 'Last Name'
      = player.input :money, as: :decimal, label: 'Money', placeholder: 'Money'
      = player.button :submit

app/views/players/index.html.slim
.box
  .box-header.with-border
    h3.box-title
  .box-body
    #table
      table.table.table-hover
        thead
          tr
            th Name
            th Last Name
            th Money
            th Status
            th Actions
        tbody
          - unless @players.empty?
            - @players.each do |player|
              tr
                td = player.name.titleize
                td = player.lastname.titleize
                td = player.money.round(3)
                td = player.status
                td = link_to "Show", player_path(player)
                td = link_to "Deactivate", player_path(player), method: :delete, data: {confirm: "Are you sure?"} 
                td = link_to "Activate", player_path(player), method: :post

= paginate @players
= link_to "Create a Player", new_player_path, class: "btn btn-primary"

app/views/players/new.html.slim
.box
  .box-header.with-border
    h3.box-title New Player
  .box-body
    = simple_form_for @player, defaults: {wrapper_html: {class: "form-group"}} do |player|
      = player.input :name, required: true, label: 'Name', placeholder: 'Name'
      = player.input :lastname, label: 'Last Name', placeholder: 'Last Name'
      = player.input :money, as: :decimal, label: 'Money', placeholder: 'Money'
      = player.button :submit

app/views/players/show.html.slim
.box
  .box-header.with-border
    h3.box-title 
  .box-body
    #table
      table.table.table-hover
        thead
          tr
            th Name
            th Last Name
            th Money
            th Status
        tbody
          tr
            td = @player.name.titleize
            td = @player.lastname.titleize
            td = @player.money.round(3)
            td = @player.status
.row
  .col-md-4
    = link_to "Edit the Player", edit_player_path, class: "btn btn-primary"
  .col-md-4
    = link_to "Activate", player_path(@player), class: "btn btn-warning", method: :post
  .col-md-4
    = link_to "Deactivate", player_path(@player), class: "btn btn-danger", method: :delete, data: {confirm: "Are you sure?"}         

app/views/rounds/index.html.slim
- unless @rounds.empty?
  - @rounds.each do |round|
    .box.box-default.collapsed-box
      .box-header.with-border
        #table
          table.table.table-hover
            thead
              tr
                th id
                th Total Bet
                th Spin Result
                th Total Payout
            tbody
              tr
                td = round.id
                td = round.total_bet.round(3)
                td = round.spin_result
                td = round.total_payout.round(3)
        .box-tools.pull-right
          button.btn.btn-box-tool data-widget="collapse"
            i.fa.fa-plus
      .box-body
        #inner-table
            table.table.table-hover
              thead
                tr
                  th Name
                  th Last Name
                  th Bet Amount
                  th Bet Color
                  th Payout
              tbody
                - bets = round.bets
                - unless bets.empty?
                  - bets.each do |bet|
                    tr
                      td = bet.player.name
                      td = bet.player.lastname
                      td = bet.amount.round(3)
                      td = bet.bet_color
                      td = bet.payout.round(3)

= paginate @rounds